{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if (and (.Values.ingress.tls) (.Values.ingress.tls.acme)) }}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{- end }}
  name: socks-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: front-end
          servicePort: 80
        path: /
    {{- if .Values.ingress.fqdn }}
    host: {{ .Values.ingress.fqdn }}
    {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.fqdn }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
